################################################################################
# This is oly's configuration file.                                            #
# Please edit the following values.                                            #
# You must at least set author, base_path and pdf_viewer.                      #
################################################################################

# the author's name in the preview and generated pdf
author: Leonhard Euler

# the base path where solutions are stored
base_path: ~/Mathematics/Solutions

# the path where figures are stored, inside of base_path
figures_dir: figures

# the markup language the solutions are typed in
# must be one of latex or typst (default latex)
lang: latex

# language setting passed to the typst preview and preamble files.
# must be a two or three letters language code
language: en

# the text editor to use
# autodected from $EDITOR and $VISUAL, fallback to vim
# editor: vim

# the pdf viewer used for 'oly gen'
pdf_viewer: zathura

# wether to open the generated pdf with pdf_viewer when running 'oly gen'
preview: true

# wether to confirm deletion or not in 'oly rm'
confirm: true

# map contest names to other ones
abbreviations:
  Shortlist: ISL

# directory structure to store contests
# available variables are: date, contest, year, problem and source
contest_format:
  Club: "Club/${date}"
  Test: "POFM/Tests/${year}/${contest} ${year} ${problem}"

# where to output the generated pdf
# defaults to ${XDG_CACHE_HOME:-~/.cache}/oly/${source}
# output_directory: ${PWD}/oly

# where temporary files are written
# defaults to ${TMPDIR:-/tmp}/oly
# OLY_TMPDIR: /tmp/oly

# added right after \documentclass in the preview file in latex
# meant to specify which latex packages to use
# packages: '\usepackage[whatever]{somepackage}'

# You can also override preamble, contents, and metadata.
# preamble is what gets put in the preview file
# contents is the content that is already written in the file
# metadata is the metadata you get prompted for in 'oly add'
# For example, you can use the following
# metadata: "\
# source: ${source}\n\
# topic:  ${topic}\n\
# tags:   []\n\
# url:    \n\
# "
